### ISSUE TITLE
novm run gets stuck when exiting bash

### ISSUE THREAD

**Issue by pwaller** [google/novm#10]
Edit: accidentally hit ctrl-enter before writing the post... apologies

```
novm --debug create --name pw-test --nofork --init --nic ip=192.168.1.2/24,gateway=192.168.1.1
```

```
foo pwaller # novm run --name pw-test --terminal bash
foo / # exit
^C^C^C
```

Now I have to go and kill `novm run` from elsewhere to reclaim my terminal.

**Comment by pwaller** [comment]
Note: after killing it, I cannot run  `novm run --name pw-test` on anything at all, it just hangs.

**Comment by pwaller** [comment]
Also note for anyone following along by email: I accidentally hit submit on the issue before writing the issue body. I've edited it in place. Apologies.

**Comment by zhurongze** [comment]
@pwaller I met the same issue and I found out the %CPU of novmm is 100% after I create a new VM.

  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 8429 root      20   0 1319m 108m  63m S 100.1  0.3   3:26.24 novmm

**Comment by zhurongze** [comment]
Hi @pwaller ， what 's your environment ？

**Comment by pwaller** [comment]
64-bit Debian 8.

**Comment by amscanne** [comment]
Thanks for the report.

The terminal code could definitely use a revisit; it's pretty hacky. I agree it would be nice to have the ability to kill things nicely if something goes wrong.

**Comment by amscanne** [comment]
I believe this is the same issue as #23. Please reopen if it isn't.
