### ISSUE TITLE
error mount_tag in novm's guest

### ISSUE THREAD

**Issue by zhurongze** [google/novm#19]
CentOS 6.5
kernel 3.12.21
qemu-kvm 2.1.2 (enable-virtfs)
go version go1.3.3 linux/amd64
Python 2.6.6

firstly, I run the novm, it print "9pnet_virtio: no channels available", so I modified lib/novm/libexec/init,  it can print the mount_tag:

......
echo "~~~ read virtio1 mount_tag ~~~"  >   /dev/kmsg  
cat /sys/bus/virtio/drivers/9pnet_virtio/virtio1/mount_tag > /dev/kmsg  
echo "~~~ read virtio2 mount_tag ~~~"  >  /dev/kmsg  
cat /sys/bus/virtio/drivers/9pnet_virtio/virtio2/mount_tag  >  /dev/kmsg  
echo "~~~ read virtio1 status ~~~"  >  /dev/kmsg 
cat /sys/bus/virtio/drivers/9pnet_virtio/virtio1/status > /dev/kmsg 
......

I run the novm again, it print the log:
......
~~~ read virtio1 mount_tag ~~~
�root~~~ read virtio2 mount_tag ~~~

init~~~ read virtio1 status ~~~
0x00000007
......

so, I think the mount_tag are error in guest, the correct mount_tag are "root" and "init" .

**Comment by amscanne** [comment]
Sorry, I was a bit aggressive in pushing a change that broke some things.

This should be corrected in bb10cddf229361394fea4c0b7c895ba15663b925.
