### ISSUE TITLE
Feature request: IPv6 support

### ISSUE THREAD

**Issue by pwaller** [google/novm#8]
Is it possible we'll see IPv6 support any time soon?

**Comment by amscanne** [comment]
The management scripts just fire up dnsmasq, and it seems as though dnsmasq (and the guest kernel, since it's Linux) both support ipv6 already.

The only thing that's necessary to properly support ipv6 would be to parse the masks properly in novm/net.py. Seems pretty straight-forward.

**Comment by pwaller** [comment]
I'm not interested in following this up for now, and it seems this project is not having any development.
